
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import os
import logging
import json

logger = logging.getLogger(__name__)

CONFIG_FILE = "email_config.json"

def load_config():
    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE, 'r') as f:
            return json.load(f)
    return None

def create_config_template():
    if not os.path.exists(CONFIG_FILE):
        template = {
            "smtp_server": "smtp.gmail.com",
            "smtp_port": 587,
            "sender_email": "YOUR_EMAIL@gmail.com",
            "sender_password": "YOUR_APP_PASSWORD",
            "receiver_email": "YOUR_EMAIL@gmail.com"
        }
        with open(CONFIG_FILE, 'w') as f:
            json.dump(template, f, indent=4)
        logger.info("Created template %s. Please edit it with your credentials.", CONFIG_FILE)

def send_email_report(attachment_path):
    """
    Sends the HTML report via email using credentials from email_config.json.
    """
    config = load_config()
    if not config:
        create_config_template()
        logger.warning("Email config not found. Created %s. Please fill it out to enable emails.", CONFIG_FILE)
        return

    sender_email = config.get("sender_email")
    sender_password = config.get("sender_password")
    receiver_email = config.get("receiver_email")
    smtp_server = config.get("smtp_server", "smtp.gmail.com")
    smtp_port = config.get("smtp_port", 587)

    if "YOUR_" in sender_email or not sender_password:
        logger.warning("Email configuration invalid (default values detected). Skipping email.")
        return

    try:
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = receiver_email
        msg['Subject'] = "Daily Stock Screener Report - Completed"

        body = "Here is your daily stock screener report generated by python."
        msg.attach(MIMEText(body, 'plain'))

        # Attachment
        if attachment_path and os.path.exists(attachment_path):
            filename = os.path.basename(attachment_path)
            with open(attachment_path, "rb") as attachment:
                part = MIMEBase('application', 'octet-stream')
                part.set_payload(attachment.read())
            
            encoders.encode_base64(part)
            part.add_header(
                "Content-Disposition",
                f"attachment; filename= {filename}",
            )
            msg.attach(part)
        else:
            logger.warning("Attachment file not found!")

        # Send
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(sender_email, sender_password)
        text = msg.as_string()
        server.sendmail(sender_email, receiver_email, text)
        server.quit()
        
        logger.info("Email sent successfully to %s", receiver_email)

    except Exception as e:
        logger.error("Failed to send email: %s", e)
